# Generated by Django 3.0.8 on 2021-10-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211031_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='deepavali-is-coming', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
